name: pucek
favicon: null
layout_spectrum: 0.049150347243994474
typography_spectrum: 0.19220677250996232
title: Bartek Pucek
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ededed'
    - '#cdcdcd'
    - '#a7a7a7'
    - '#5b5b5b'
  brandStrength: 0.37424180028028786
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
